### ISSUE TITLE
拜托，css这样实现多行文本“展开收起” 超酷的好吧

### ISSUE THREAD

**Issue by Sunny-lucking** [Sunny-lucking/interview#18]
## 前言

2022.02.14的午后，我站在你家门口，再次遇见了你，他又来牵起你的手

无法言语，我是什么，这样傻傻的我怎么守护你

这次我静静哭了选择放弃，我好想好想把记忆折叠起

可惜，记忆不能像之前那个需求一样自由展开与折叠

前段时间接到一个需求，关于文字展开和收起的，走了很多路,踩了很多坑。

在这个夜深人静，想你想到泪流的时候，决定记录分享一下。

需求如下所述：

1. **未满两行时**
![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/ff49acc33912403c9a9644d5d45dbb88~tplv-k3u1fbpfcp-zoom-1.image)

2. **超过两行，少于7行时**

未展开

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/1d9efa0d88444b0c993febc752f6cb8f~tplv-k3u1fbpfcp-zoom-1.image)

展开

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/fa893d18e0da4e62b480d87e0f482904~tplv-k3u1fbpfcp-zoom-1.image)

3. **超过7行时**

未展开

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/83d6a1a825f14412a00fe39df3c17985~tplv-k3u1fbpfcp-zoom-1.image)

展开

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/fc4e44ed8d244eada1e783b6ac43588f~tplv-k3u1fbpfcp-zoom-1.image)

就如上面所述，我倒是第一次做这种需求，于是就网上搜索下案例，然后就搜出下面这篇文章：

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/c026223a6f2a4ca6ae6c553cd3933112~tplv-k3u1fbpfcp-zoom-1.image)

>文章链接：https://juejin.cn/post/6963904955262435336#comment

点赞和评论都挺多的，于是就用他的方案来实现了。

但是后面发现有些问题，其实他的文章后面的评论区也有读者提出来了问题。

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/b96901c083a643c8b2363581950dabcf~tplv-k3u1fbpfcp-zoom-1.image)

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/5cb7a5c51ea5488a9afb9367d3ee8e0f~tplv-k3u1fbpfcp-zoom-1.image)

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/9a25f5f736804e9ea9dd07ab84c83683~tplv-k3u1fbpfcp-zoom-1.image)

其实我觉得问题也不大，于是问哦下设计大佬

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/ac395693dd4f4c44bf34817fe6d17a37~tplv-k3u1fbpfcp-zoom-1.image)

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/6652c506059e44b4ae1550e3d05f2918~tplv-k3u1fbpfcp-zoom-1.image)

显然，就收到了拒绝。

被拒绝是十分正常不过的事情了，不过这比被发好人卡杀伤力少太多了，不信你听听：

"你真的挺好的，人也很优秀，但是配不上我"

这矫情的措辞结构

经历过的人会懂

可能是孤独让情绪变得脆弱，毫无头绪的我，开始寻求网友的帮助。

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/ad45a7361c234b3d9a909ed9118e0539~tplv-k3u1fbpfcp-zoom-1.image)

群里就有大佬提供了这个

https://codepen.io/xboxyan/pen/LYWpWzK

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/9e82f3f80faf4c6bad7b7e99d267f958~tplv-k3u1fbpfcp-zoom-1.image)

这个跟方法跟 上面介绍的那篇文章的方法差不多

不同点在于这个方法是利用div高度来限制文字显示的行数的。
![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/b3a641bcf3564f71a38beb5931975c31~tplv-k3u1fbpfcp-zoom-1.image)

上面文章里是利用-webkit-line-clamp来限制行数。
![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/f77df27307744d12a867d14231496811~tplv-k3u1fbpfcp-zoom-1.image)

然后它的省略号也是在label按钮里模拟出来的。

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/aca9bebdac31445cbd2fd1d9c02322b9~tplv-k3u1fbpfcp-zoom-1.image)

上面文章里的方法的缺点上面已经说了，那么群里推荐的方法是否也能解决问题呢？

其实不行，本来在pc上看确实是没问题了，但是在安卓和ios看发现不太行。

发现在ios上限制7行的时候，显示除了7.5行，就是多了半行。或者 总有一个手机对不齐（我们要适配各种安卓机和低端ios）

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/1cd086754d6b4ccc8f450ae694b8886c~tplv-k3u1fbpfcp-zoom-1.image)

虽说两个方法都有缺点，但是都有优点，于是结合两者的优点就进行了我的方案的实现。

## 我的方案

```html
<div class="activity-desc-wrapper">
  <input
    type="checkbox"
    class="toggleInput"
    id="toggleInput"
    v-model="isUnFold"
  />
  <div class="activity-desc" ref="descBox" id="descBox">
    <label
      class="btn"
      for="toggleInput"
      v-if="isMoreThan2Line && (!isUnFold || isMoreThan7Line)"
      >{{ isUnFold ? '展开' : '收起' }}</label
    >
    概述文字概述文字概述文字概述文字概
    述文字概述文字概述文字概述文字概述文字概述文字
    <label
      class="btn-no-absolute"
      for="toggleInput"
      v-if="isUnFold && !isMoreThan7Line"
      >收起</label
    >
  </div>
</div>
```

首先，跟上面那篇文章里介绍的一样，用input来记录当前是展开还是收起状态，

不同点是我用了两个label按钮。

一个`label`是不用定位的，直接跟在文字的末尾。这种是作为文字超过两行，但是未超过七行，展开的状态。

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/85dc5ad3ae5943c38d46b0b2374af3f2~tplv-k3u1fbpfcp-zoom-1.image)

前面的label则是绝对定位到文字盒子的末尾。作为 文字超过两行未展开，展开后文字超过七行的情况。

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/faf6cc0a18544f90b8af3dc3e3f68133~tplv-k3u1fbpfcp-zoom-1.image)

![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/2a4d38f6dcbd4a948552408200e5a7e7~tplv-k3u1fbpfcp-zoom-1.image)

可以看下css的实现

```css
.activity-desc-wrapper {
  display: flex;
  .toggleInput {
    display: none;
  }
  .toggleInput:checked + .activity-desc {
    -webkit-line-clamp: 7;
  }

  .activity-desc {
    padding: 0;
    position: relative;
    margin-top: 7px;
    font-size: 24px;
    font-weight: 400;
    color: #8a8f99;
    line-height: 1.2;

    display: -webkit-box;
    overflow: hidden;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;

    .btn {
      position: absolute;
      padding: 0 3px 0 7px;
      font-weight: 400;
      bottom: 0px;
      right: 0;
      line-height: 1.2;
      font-size: 24px;
      color: #939fe1;
      background: #f5f7fa;
      &::before {
        content: '...';
        color: #8a8f99;
        transform: translateX(-100%);
      }
    }
    .btn-no-absolute {
      float: none;
      font-size: 24px;
      font-weight: 400;
      color: #939fe1;
    }
  }
}
```

我的方案的另一个重点在于**判断文字是否超过2行和七行**，这个就在于获取文字的实际高度是多少，一开始以为是没办法获取的，只能获取到省略后的文字高度，在随便调试了一下之后，发现**scrollHeight**属性就可以获取到盒子的实际高度了，

```js
mounted() {
  // 判断文案实际行数
  this.$nextTick(() => {
    const height = this.$refs.descBox.scrollHeight;
    const lineHeight = +window
      .getComputedStyle(this.$refs.descBox)
      .lineHeight.match(/\d+\.*\d+/g)[0];
    this.isMoreThan7Line = height / lineHeight > 7;
    this.isMoreThan2Line = height / lineHeight > 2;
  });
},
```
完美，收获了一帮小迷妹。
![](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/546650f7433c4d8a8c78bced348ca4dd~tplv-k3u1fbpfcp-zoom-1.image)

## 总结

1. 跟在文字后面的按钮可以不设置定位
2. 处于文字行数末尾的按钮可以设置绝对定位然后
3. 行数的判断可以用scrollHeight属性
4. 利用伪元素来模拟省略号...

回忆起从前，我的心总是默默的等候

你曾经说你 想找一个依靠

等了好几天 等你的留言 却发现是空白一片

站在镜子前 是不是我的样子有点丑
